### ISSUE TITLE
updateApiVersions 报错 [ERROR] [10753] Unknown[385]

### ISSUE THREAD

**Issue by bearzlh** [swoole/phpkafka#72]
* 你遇到了什么问题？
报错日志如下，多发于hyperf一段时间无访问时再次访问出错。频繁访问没有报错
PHP Warning:  Uninitialized string offset 0 in /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php on line 41

Warning: Uninitialized string offset 0 in /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Protocol/Type/UVarInt.php on line 41
[ERROR] [10753] Unknown[385] in /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Protocol/ErrorCode.php
[ERROR] #0 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Client/SyncClient.php(196): longlang\phpkafka\Protocol\ErrorCode::check(10753)
#1 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Client/SyncClient.php(103): longlang\phpkafka\Client\SyncClient->updateApiVersions()
#2 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Client/SwooleClient.php(52): longlang\phpkafka\Client\SyncClient->connect()
#3 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Broker.php(174): longlang\phpkafka\Client\SwooleClient->connect()
#4 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Broker.php(156): longlang\phpkafka\Broker->getClientByBrokerId(1001)
#5 /www/hyperf-skeleton/vendor/longlang/phpkafka/src/Producer/Producer.php(160): longlang\phpkafka\Broker->getClient(1001)
#6 /www/hyperf-skeleton/vendor/hyperf/kafka/src/Producer.php(94): longlang\phpkafka\Producer\Producer->sendBatch(Array)
#7 [internal function]: Hyperf\Kafka\Producer->Hyperf\Kafka\{closure}()
#8 /www/hyperf-skeleton/vendor/hyperf/kafka/src/Producer.php(148): Closure->call(Object(Hyperf\Kafka\Producer))
#9 {main}

* Kafka 环境是自建还是云服务？
docker环境
cat docker-compose.yml
```
version: '2'
services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2182:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on: [ zookeeper ]
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.90
      KAFKA_CREATE_TOPICS: "cps_static:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_HOME: "/opt/kafka_2.12-2.4.1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
  kafka-manager:
    image: kafkamanager/kafka-manager
    depends_on:
      - zookeeper
    ports:
      - "8084:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
```

* 请执行下面的命令获取环境信息。
> `php -v & php --ri swoole & composer info | grep longlang/phpkafka`

```
[1] 72185
[2] 72186
PHP 8.0.12 (cli) (built: Oct 21 2021 14:38:26) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.12, Copyright (c) Zend Technologies
    with Yasd v0.3.9-alpha, Our Copyright, by codinghuang
[1]  - 72185 done       php -v

swoole

Swoole => enabled
Author => Swoole Team <team@swoole.com>
Version => 5.0.0
Built => Aug 23 2022 18:14:26
coroutine => enabled with boost asm context
kqueue => enabled
rwlock => enabled
openssl => OpenSSL 3.0.0 7 sep 2021
dtls => enabled
http2 => enabled
json => enabled
curl-native => enabled
pcre => enabled
zlib => 1.2.11
brotli => E16777225/D16777225
mysqlnd => enabled
async_redis => enabled

Directive => Local Value => Master Value
swoole.enable_coroutine => On => On
swoole.enable_library => On => On
swoole.enable_preemptive_scheduler => Off => Off
swoole.display_errors => On => On
swoole.use_shortname => Off => Off
swoole.unixsock_buffer_size => 262144 => 262144
[2]  + 72186 done       php --ri swoole
longlang/phpkafka                       v1.2.1  A kafka client. Support php-fpm and Swoole.

```

* 提供最小可复现代码：

```php
无法复现
```
